### ISSUE TITLE
Create category page

### ISSUE THREAD

**Issue by emilps** [emilps/fjelltg#7]
Create a category page which contains the different categories of products. Shall link to the product page.  You can get the info about the products from the cms.

**Comment by emilps** [comment]
Duplicate #6

**Comment by eirikdahlen** [comment]
I think this is not duplicating #6 after all. 

We have the ProductRoll which should be remamed `ProductCategoryRoll` and then within each category the option to choose each Product. 
So we need a relation between products and categories
